openapi: 3.0.3
info:
  title: curriculum
  version: 1.0.0.1
paths:
  /curriculum/:
    get:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/curriculum'
components:
  schemas:
    curriculum:
      description: >-
        A Learning resource or other activity that is on a persons career or
        learning roadmap
      required:
        - _id
      properties:
        _id:
          description: The unique identifier for a resource used by a person
          type: string
        version:
          description: Scehma Version (only on Version document)
          pattern: ^[^\s]{0,32}$
          type: string
        personId:
          description: The ID of the person this item was asigned to
          type: string
        resourceId:
          description: The ID of the resource asigned
          type: string
        adhoc:
          description: >-
            This is an adhoc assignment. This document will not have a
            resourceId and will use a one-off name/link
          type: boolean
        name:
          description: The Resource Shrot Name for adhoc resources
          pattern: ^[^\s]{0,32}$
          type: string
        link:
          description: The Resource Link for adhoc resources
          pattern: >-
            ^(https?:\/\/)([a-zA-Z0-9-]{1,63}\.)+[a-zA-Z-]{2,24}(:[0-9]{1,5})?(\/(([\w\-\.~]|%[a-fA-F0-9]{2}|[!\$&'\(\)\*\+,;=:@])*\/?)*)?
          type: string
        roadmapGroup:
          description: The top level grouping Now, Next, Later, Celebrated
          enum:
            - Now
            - Next
            - Later
            - Celebrated
          type: string
        status:
          description: Archived, Assigned, Started, Completed
          enum:
            - Archived
            - Assigned
            - Started
            - Complete
          type: string
        statusDate:
          description: Date the status was last changed
          type: string
        started:
          description: Date/time the link was clicked
          type: string
        completed:
          description: Date/time the item was checked off
          type: string
        rating:
          description: Rating 0-5
          minimum: 0
          maximum: 5
          type: number
        review:
          description: Free text review of the persons experience with this resource
          maxLength: 256
          type: string
        lastSaved:
          description: Tracking information for updates
          properties:
            fromIp:
              description: Http Request remote IP address
              pattern: >-
                ^(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}$
              type: string
            byUser:
              description: UUID Of User
              type: string
            atTime:
              description: The date-time when last updated
              type: string
            correlationId:
              description: The logging correlation ID of the update transaction
              type: string
          additionalProperties: false
          type: object
      additionalProperties: false
      type: object
